<a href="https://colab.research.google.com/github/CustlyNotts/machine-learning/blob/main/ml_zoomcamp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
np.arange(3, 10)
#Array range

array([3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 1, 11)
# Creates an array of size 11 with numbers between 0 & 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

n

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [16]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 2,  3,  4],
       [ 3,  4,  5]])

In [22]:
n[2]

array([3, 4, 5])

In [24]:
n[2] = [777,555,3]
n

array([[  1,  20,   3],
       [  2,   3,   4],
       [777, 555,   3]])

In [25]:
n[:,1]

array([ 20,   3, 555])

In [31]:
np.random.rand(5,2)
# Array of random numbers

array([[0.30524666, 0.81988539],
       [0.43131529, 0.10061873],
       [0.84645369, 0.85578965],
       [0.30645084, 0.08488173],
       [0.20936998, 0.42289203]])

In [34]:
np.random.seed(10)
np.random.rand(5,2)
# The seed ensures that the same set of random numbers are returned once its been generated

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [35]:
np.random.randn(5,2)
# Real numbers -ve & +ve

array([[ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737],
       [-0.96506567,  1.02827408],
       [ 0.22863013,  0.44513761]])

In [36]:
np.random.rand(5,2) * 5

array([[2.71272184, 0.71085024],
       [1.8667038 , 3.37066808],
       [2.20916587, 2.17006997],
       [3.08883489, 2.56569121],
       [3.25198591, 3.00519477]])

In [42]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(10, 4))
# Random integers

array([[40, 15, 72, 22],
       [43, 82, 75,  7],
       [34, 49, 95, 75],
       [85, 47, 63, 31],
       [90, 20, 37, 39],
       [67,  4, 42, 51],
       [38, 33, 58, 67],
       [69, 88, 68, 46],
       [70, 95, 83, 31],
       [66, 80, 52, 76]])

In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [44]:
a + 1
# Add an element toeach number

array([1, 2, 3, 4, 5])

In [45]:
a * 2
# Multiply each element by 2

array([0, 2, 4, 6, 8])

In [49]:
b = (a *3) / 2
b

array([0. , 1.5, 3. , 4.5, 6. ])

In [50]:
a + b

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [51]:
a > 2

array([False, False, False,  True,  True])

In [53]:
b > a

array([False,  True,  True,  True,  True])

In [54]:
b[b > a]
# Returns elements in b for which (b > a) is true

array([1.5, 3. , 4.5, 6. ])

In [56]:
a.min()

np.int64(4)

In [58]:
a.max()

np.int64(4)

In [59]:
a.sum()

np.int64(10)

Dot Product

In [61]:
u = np.array([2,3,4,5,6])
u

array([2, 3, 4, 5, 6])

In [62]:
v = np.array([7,6,1,0,1])
v

array([7, 6, 1, 0, 1])

In [63]:
# Dot product
def vector_vector_multiplication(u,v):
  assert u.shape[0] == v.shape[0]

  n = u.shape[0]

  result = 0.0

  for i in range(n):
    result = result + u[i] * v[i]

  return result

In [64]:
# Perform dot Product of u & v
vector_vector_multiplication(u, v)

np.float64(42.0)

In [65]:
# Same operation
u.dot(v)

np.int64(42)